"""Strategy Agent Tools - Strategy Generation"""
import json
from pathlib import Path
from datetime import datetime
from strands import tool


@tool
def generate_strategy(
    analysis_data: str,
    strategy_type: str,
    output_file: str,
    reference_rules: str = None
) -> str:
    """
    Generate a project-specific strategy document.
    
    Args:
        analysis_data: JSON or text with analysis results
        strategy_type: 'transform', 'validate', 'test', or 'general'
        output_file: Output file path (e.g., 'output/strategy/transform_strategy.md')
        reference_rules: Path to static rules file (for deduplication check)
    
    Returns:
        Success message with file path
    
    Workflow:
        1. Agent generates strategy content
        2. Tool validates against reference rules (deduplication)
        3. Tool saves final strategy file
    """
    # Parse analysis data
    try:
        data = json.loads(analysis_data)
    except (json.JSONDecodeError, TypeError):
        data = {'raw_data': analysis_data}
    
    # Read reference rules if provided
    reference_content = ""
    if reference_rules:
        ref_path = Path(reference_rules)
        if ref_path.exists():
            reference_content = ref_path.read_text(encoding='utf-8')
    
    # Prepare output path
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Return instruction for Agent to generate content
    result = {
        'status': 'ready_to_generate',
        'output_file': str(output_path),
        'strategy_type': strategy_type,
        'analysis_data': data,
        'reference_rules_preview': reference_content[:500] + '...' if reference_content else None,
        'instruction': """
Generate strategy content following these steps:

1. Analyze Top 10 SQLs from analysis_data
2. For each Phase (1-4), determine:
   - Is general rule sufficient? → Write "*(패턴 없음)*"
   - Need project-specific guidance? → Add pattern with Before/After SQL
3. Call write_strategy_file() with your generated content
4. Tool will validate for duplicates with reference rules
5. Tool will save final strategy file
"""
    }
    
    return json.dumps(result, ensure_ascii=False, indent=2)


@tool
def write_strategy_file(output_file: str, content: str, reference_rules: str = None) -> str:
    """
    Write generated strategy content to file after validation.
    
    Args:
        output_file: Output file path
        content: Strategy content generated by Agent
        reference_rules: Path to reference rules (for deduplication check)
    
    Returns:
        Success message with validation results
    
    Validation:
        - Checks for duplicate patterns with reference rules
        - Warns if general rule content detected
        - Saves file with validation report
    """
    
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Validate against reference rules
    validation_result = _validate_strategy_content(content, reference_rules)
    
    # Add timestamp
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
    final_content = content.replace('[timestamp]', timestamp)
    
    output_path.write_text(final_content, encoding='utf-8')
    
    result = f"✅ Strategy saved: {output_path.resolve()}\n"
    
    if validation_result['warnings']:
        result += f"\n⚠️ {len(validation_result['warnings'])} warnings:\n"
        for warning in validation_result['warnings']:
            result += f"  - {warning}\n"

    # Update strategy section in source_analysis.md
    try:
        from agents.source_analyzer.tools.report_generator import _generate_strategy_section
        from utils.project_paths import REPORTS_DIR
        import re as _re
        analysis_report = REPORTS_DIR / "source_analysis.md"
        if analysis_report.exists():
            report_content = analysis_report.read_text(encoding='utf-8')
            new_section = _generate_strategy_section()
            strategy_marker = "## 3.5 Migration Strategy"
            if strategy_marker in report_content:
                before = report_content[:report_content.index(strategy_marker)]
                # Preserve sections after strategy (## 4. Recommendations, etc.)
                after_match = _re.search(r'\n(## 4\. )', report_content[report_content.index(strategy_marker):])
                after = ""
                if after_match:
                    after_start = report_content.index(strategy_marker) + after_match.start()
                    after = "\n" + report_content[after_start:]
                analysis_report.write_text(before + new_section + after, encoding='utf-8')
                result += "✅ source_analysis.md 전략 섹션 업데이트 완료\n"
    except Exception as e:
        result += f"⚠️ source_analysis.md 업데이트 실패: {e}\n"

    return result


def _validate_strategy_content(content: str, reference_rules: str = None) -> dict:
    """
    Validate strategy content for duplicates with reference rules.
    
    Returns:
        {
            'duplicate_count': int,
            'warnings': [str],
            'is_valid': bool
        }
    """
    warnings = []
    duplicate_count = 0
    
    if not reference_rules:
        return {'duplicate_count': 0, 'warnings': [], 'is_valid': True}
    
    ref_path = Path(reference_rules)
    if not ref_path.exists():
        return {'duplicate_count': 0, 'warnings': [], 'is_valid': True}
    
    ref_content = ref_path.read_text(encoding='utf-8')
    
    # Check for simple conversion patterns (should NOT be in strategy)
    simple_patterns = [
        ('NVL', 'COALESCE'),
        ('DECODE', 'CASE'),
        ('SYSDATE', 'CURRENT_TIMESTAMP'),
        ('DUAL', 'remove')
    ]
    
    for oracle_pattern, pg_pattern in simple_patterns:
        # If strategy has simple "A → B" format, it's likely duplicate
        if f"{oracle_pattern} → {pg_pattern}" in content or f"{oracle_pattern}→{pg_pattern}" in content:
            warnings.append(f"단순 변환 중복: {oracle_pattern} → {pg_pattern}")
            duplicate_count += 1
    
    is_valid = duplicate_count < 2
    
    return {
        'duplicate_count': duplicate_count,
        'warnings': warnings,
        'is_valid': is_valid
    }
